#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-csi
  namespace: kube-system
  labels: #@ labels("token")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@ if len(data.values.hcloud_token) == 0 or data.values.hcloud_token == "invalid":
  #@  assert.fail("hcloud_token is missing or invalid")
  #@ end
  token: #@ data.values.hcloud_token
