#@data/values
---
#@overlay/match missing_ok=True
configuration:
  ingress:
    domains:
    - "jamesclonk.com"

  postgres:
    backup:
      s3:
        enabled: "true"
        retention_days: "7d"

  alertmanager:
    email:
      enabled: "true"
    teams_webhook:
      enabled: "true"

  msteams:
    enabled: "true"

#@overlay/match missing_ok=True
dashboard:
  #@overlay/match missing_ok=True
  kubeconfig_enabled: "false"
