---
version: '3'
set: [errexit, nounset, pipefail]

tasks:
  default:
    desc: "List all tasks"
    cmds:
    - task -l

  deploy:
    desc: "Render the templates"
    cmds:
    - task: plato render

  vendor:
    desc: "Vendor all files"
    cmds:
    - vendir sync
    - bash templates/dex/build/update.sh
    - bash templates/grafana/build/update.sh
    - bash templates/headlamp/build/update.sh
    - bash templates/loki/build/update.sh
    - bash templates/prometheus/build/update.sh
    - bash templates/vector/build/update.sh
