---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0

directories:
- path: vendor/github.com/kubernetes/ingress-nginx
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/ingress-nginx
      ref: helm-chart-4.14.1
    includePaths:
    - deploy/static/provider/cloud/*
- path: ingress-nginx/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/ingress-nginx/deploy/static/provider/cloud
    includePaths:
    - deploy.yaml
    excludePaths:
    - LICENSE
    - kustomization.yaml

- path: vendor/github.com/oauth2-proxy/manifests
  contents:
  - path: .
    git:
      url: https://github.com/oauth2-proxy/manifests
      ref: oauth2-proxy-9.0.1
    includePaths:
    - helm/oauth2-proxy/**/*
- path: oauth2-proxy/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/oauth2-proxy/manifests/helm/oauth2-proxy
    excludePaths:
    - LICENSE

- path: vendor/github.com/jetstack/cert-manager
  contents:
  - path: .
    githubRelease:
      slug: jetstack/cert-manager
      tag: v1.9.1
      disableAutoChecksumValidation: true
    includePaths:
    - cert-manager.yaml
- path: cert-manager/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/jetstack/cert-manager
    includePaths:
    - cert-manager.yaml
    excludePaths:
    - LICENSE

- path: vendor/github.com/kubernetes/dashboard
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/dashboard
      ref:  v2.6.1
    includePaths:
    - aio/deploy/*
- path: kubernetes-dashboard/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/dashboard/aio/deploy
    includePaths:
    - recommended.yaml
    excludePaths:
    - LICENSE

- path: vendor/github.com/kubernetes/kube-state-metrics
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/kube-state-metrics
      ref: v2.6.0
    includePaths:
    - examples/standard/*
- path: monitoring/kube-state-metrics/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/kube-state-metrics/examples/standard
    excludePaths:
    - LICENSE

- path: vendor/github.com/prometheus-community/helm-charts
  contents:
  - path: .
    git:
      url: https://github.com/prometheus-community/helm-charts
      ref: prometheus-15.16.1
    includePaths:
    - charts/prometheus/**/*
- path: monitoring/prometheus/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/prometheus-community/helm-charts/charts/prometheus
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/grafana
  contents:
  - path: .
    git:
      url: https://github.com/grafana/helm-charts
      ref: grafana-6.42.2
    includePaths:
    - charts/grafana/**/*
- path: monitoring/grafana/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/grafana/charts/grafana
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/promtail
  contents:
  - path: .
    git:
      url: https://github.com/grafana/helm-charts
      ref: promtail-6.5.1
    includePaths:
    - charts/promtail/**/*
- path: monitoring/loki/build/charts/promtail
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/promtail/charts/promtail
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/loki
  contents:
  - path: .
    git:
      url: https://github.com/grafana/helm-charts
      ref: loki-2.16.0
    includePaths:
    - charts/loki/**/*
- path: monitoring/loki/build/charts/loki
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/loki/charts/loki
    excludePaths:
    - LICENSE
