---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0

directories:
- path: vendor/github.com/kubernetes-sigs/metrics-server
  contents:
  - path: .
    githubRelease:
      slug: kubernetes-sigs/metrics-server
      tag: v0.5.2
      disableAutoChecksumValidation: true
    includePaths:
    - components.yaml
- path: metrics-server/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes-sigs/metrics-server
    includePaths:
    - components.yaml

- path: vendor/github.com/hetznercloud/csi-driver
  contents:
  - path: .
    git:
      url: https://github.com/hetznercloud/csi-driver
      ref: v1.5.1
    includePaths:
    - deploy/kubernetes/*
- path: hcloud-csi/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/hetznercloud/csi-driver/deploy/kubernetes
    includePaths:
    - hcloud-csi.yml
    excludePaths:
    - LICENSE

- path: vendor/github.com/kubernetes/ingress-nginx
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/ingress-nginx
      ref: helm-chart-3.39.0
    includePaths:
    - deploy/static/provider/baremetal/*
- path: ingress-nginx/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal
    includePaths:
    - deploy.yaml
    excludePaths:
    - LICENSE
    - kustomization.yaml

- path: vendor/github.com/oauth2-proxy/manifests
  contents:
  - path: .
    git:
      url: https://github.com/oauth2-proxy/manifests
      ref: oauth2-proxy-4.2.2
    includePaths:
    - helm/oauth2-proxy/**/*
- path: oauth2-proxy/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/oauth2-proxy/manifests/helm/oauth2-proxy
    excludePaths:
    - LICENSE

- path: vendor/github.com/jetstack/cert-manager
  contents:
  - path: .
    githubRelease:
      slug: jetstack/cert-manager
      tag: v1.6.1
      disableAutoChecksumValidation: true
    includePaths:
    - cert-manager.yaml
- path: cert-manager/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/jetstack/cert-manager
    includePaths:
    - cert-manager.yaml
    excludePaths:
    - LICENSE

- path: vendor/github.com/kubernetes/dashboard
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/dashboard
      ref: v2.0.5
    includePaths:
    - aio/deploy/*
- path: kubernetes-dashboard/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/dashboard/aio/deploy
    includePaths:
    - recommended.yaml
    excludePaths:
    - LICENSE

- path: vendor/github.com/kubernetes/kube-state-metrics
  contents:
  - path: .
    git:
      url: https://github.com/kubernetes/kube-state-metrics
      ref: v2.2.4
    includePaths:
    - examples/standard/*
- path: monitoring/kube-state-metrics/templates/upstream
  contents:
  - path: .
    directory:
      path: vendor/github.com/kubernetes/kube-state-metrics/examples/standard
    excludePaths:
    - LICENSE

- path: vendor/github.com/prometheus-community/helm-charts
  contents:
  - path: .
    git:
      url: https://github.com/prometheus-community/helm-charts
      ref: prometheus-11.16.8
    includePaths:
    - charts/prometheus/**/*
- path: monitoring/prometheus/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/prometheus-community/helm-charts/charts/prometheus
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/helm-charts
  contents:
  - path: .
    git:
      url: https://github.com/grafana/helm-charts
      ref: grafana-6.1.3
    includePaths:
    - charts/grafana/**/*
- path: monitoring/grafana/build/chart
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/helm-charts/charts/grafana
    excludePaths:
    - LICENSE

- path: vendor/github.com/grafana/loki
  contents:
  - path: .
    git:
      url: https://github.com/grafana/loki
      ref: v2.0.0
    includePaths:
    - production/helm/loki/**/*
    - production/helm/promtail/**/*
- path: monitoring/loki/build/charts/loki
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/loki/production/helm/loki
    excludePaths:
    - LICENSE
- path: monitoring/loki/build/charts/promtail
  contents:
  - path: .
    directory:
      path: vendor/github.com/grafana/loki/production/helm/promtail
    excludePaths:
    - LICENSE
