#@data/values
---
dashboard:
  enable_network_policy: true
  replicas: 1
  image: ghcr.io/headlamp-k8s/headlamp:v0.40.1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 128Mi
