#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "DaemonSet", "metadata":{"name":"vector"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"vector"}), expects=1
      - name: vector
        #@overlay/match missing_ok=True
        securityContext:
          #@overlay/match missing_ok=True
          privileged: false
          #@overlay/match missing_ok=True
          allowPrivilegeEscalation: false
