#@ load("@ytt:overlay", "overlay")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  admin-user: "{{{ .grafana.username }}}"
  admin-password: "{{{ .grafana.password }}}"

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata":{"name":"grafana"}}), expects=1
---
data:
  #@yaml/text-templated-strings
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki.loki.svc.cluster.local:3100
      isDefault: true
    - name: home-info
      type: postgres
      url: postgres.postgres.svc.cluster.local:5432
      isDefault: true
      user: grafana
      database: home_info
      secureJsonData:
        password: "{{{ .grafana.db_password }}}"
      jsonData:
        sslmode: "disable"
        maxOpenConns: 5
        maxIdleConns: 2
        postgresVersion: 1200
