#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: prometheus
  labels: #@ labels("ingress")
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: http://basic-auth.ingress-nginx.svc.cluster.local:8080
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Ingress"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization "";
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - secretName: prometheus-ingress-tls
    hosts:
    #@ for host in data.values.domains:
    - #@ "prometheus." + host
    - #@ "alertmanager." + host
    #@ end
  rules:
  #@ for/end host in data.values.domains:
  - host: #@ "prometheus." + host
    http:
      paths:
      - backend:
          serviceName: prometheus-server
          servicePort: 80
  #@ for/end host in data.values.domains:
  - host: #@ "alertmanager." + host
    http:
      paths:
      - backend:
          serviceName: prometheus-alertmanager
          servicePort: 80
