#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"prometheus-server"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"prometheus-server"}), expects=1
      - name: prometheus-server
        #@overlay/replace
        resources: #@ data.values.prometheus.resources
