#@data/values
---
domains:
- "${INGRESS_DOMAIN}"

monitoring:
  enable_network_policy: true

grafana:
  username: "${GRAFANA_USERNAME}"
  password: "${GRAFANA_PASSWORD}"

alertmanager:
  email:
    enabled: ${PROMETHEUS_ALERTMANAGER_EMAIL_ENABLED}
    host: "${PROMETHEUS_ALERTMANAGER_EMAIL_HOST}"
    mail_from: "${PROMETHEUS_ALERTMANAGER_EMAIL_FROM}"
    mail_to: "${PROMETHEUS_ALERTMANAGER_EMAIL_TO}"
    password: "${PROMETHEUS_ALERTMANAGER_EMAIL_PASSWORD}"
  teams_webhook:
    enabled: ${PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_ENABLED}
    url: "${PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_URL}"

msteams:
  enabled: ${PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_ENABLED}
  replicas: 1

kube_state_metrics:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
