#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.configuration.msteams.enabled:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams-card-template
  namespace: prometheus
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
data:
  card.tmpl: |
    {{ define "teams.card" }}
    {
       "type":"message",
       "attachments":[
          {
             "contentType":"application/vnd.microsoft.card.adaptive",
             "contentUrl":null,
             "content":{
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.6",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Prometheus Alert ({{ .Status | title }}) - {{ .CommonLabels.alertname }}{{- if .CommonLabels.job -}} for {{ .CommonLabels.job }}{{ end }}",
                        "size": "Large"
                    },
                    {
                        "type": "TextBlock",
                        "text": "{{- if eq .CommonAnnotations.summary "" -}}
                      {{- if eq .CommonAnnotations.message "" -}}
                        {{- if eq .CommonLabels.alertname "" -}}
                          Prometheus Alert
                        {{- else -}}
                          {{- .CommonLabels.alertname -}}
                        {{- end -}}
                      {{- else -}}
                        {{- .CommonAnnotations.message -}}
                      {{- end -}}
                  {{- else -}}
                      {{- .CommonAnnotations.summary -}}
                  {{- end -}}",
                        "weight": "Bolder",
                        "color": "Warning",
                        "fontType": "Monospace",
                        "size": "Medium",
                        "isSubtle": false,
                        "separator": true,
                        "wrap": true
                    }{{$externalUrl := .ExternalURL}}
                    {{- range $index, $alert := .Alerts }}
                    ,{
                        "type": "TextBlock",
                        "text": "[{{ $alert.Annotations.description }}]({{ $externalUrl }})",
                        "size": "Medium",
                        "fontType": "Monospace",
                        "separator": true
                    }
                    {{- range $key, $value := $alert.Annotations }}
                    ,{
                        "type": "TextBlock",
                        "text": "**{{ $key }}**: {{ $value }}",
                        "size": "Small"
                    }
                    {{- end }}
                    {{- range $key, $value := $alert.Labels }}
                    ,{
                        "type": "TextBlock",
                        "text": "**{{ $key }}**: {{ $value }}",
                        "size": "Small"
                    }
                    {{- end }}
                    {{- end }}
                ]
             }
          }
       ]
    }
    {{ end }}
#@ end
