#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.configuration.msteams.enabled:
#@ if len(data.values.secrets.alertmanager.teams_webhook.url) == 0 or data.values.secrets.alertmanager.teams_webhook.url == "http://example/deadbeef":
#@  assert.fail("secrets.alertmanager.teams_webhook.url is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-msteams-config
  namespace: prometheus
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
#@yaml/text-templated-strings
stringData:
  connectors.yml: |
    connectors:
    - msteams: (@= data.values.secrets.alertmanager.teams_webhook.url @)
    connectors_with_custom_templates: []
#@ end
