#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.msteams.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-msteams-config
  namespace: prometheus
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
#@yaml/text-templated-strings
stringData:
  #@ if len(data.values.alertmanager.teams_webhook.url) == 0:
  #@  assert.fail("alertmanager.teams_webhook.url cannot be empty")
  #@ end
  connectors.yml: |
    connectors:
    - msteams: (@= data.values.alertmanager.teams_webhook.url @)
    connectors_with_custom_templates: []
#@ end
