#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yml", "labels")

#@ if data.values.msteams.enabled:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-msteams
  namespace: prometheus-msteams
  labels: #@ labels()
#@ end
