#@ load("@ytt:assert", "assert")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ if len(data.values.lets_encrypt.prod_key) > 0 and data.values.lets_encrypt.prod_key != "none":
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
  annotations:
    kapp.k14s.io/change-group.letsencrypt-prod: secret
    kapp.k14s.io/change-rule.letsencrypt: upsert after upserting deployments
type: Opaque
data:
  tls.key: #@ data.values.lets_encrypt.prod_key
#@ end

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
  annotations:
    kapp.k14s.io/change-group.letsencrypt-prod: clusterissuer
    kapp.k14s.io/change-rule.letsencrypt-prod: upsert after upserting secret
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #@ if len(data.values.lets_encrypt.email) == 0 or data.values.lets_encrypt.email == "nobody@nobody":
    #@  assert.fail("lets_encrypt.email is missing or invalid")
    #@ end
    email: #@ data.values.lets_encrypt.email
    #@ if/end len(data.values.lets_encrypt.prod_key) > 0 and data.values.lets_encrypt.prod_key != "none":
    disableAccountKeyGeneration: true
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

#@overlay/match by=overlay.subset({"kind":"Deployment"}), expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group.letsencrypt: deployments

#@overlay/match by=overlay.subset({"kind":"Service"}), expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group.letsencrypt: deployments
