#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-server
  namespace: prometheus
  labels: #@ labels("httproute")
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
    sectionName: prometheus
  hostnames:
  - prometheus.{{{ .environment.domain }}}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus-server
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: Strict-Transport-Security
          value: "max-age=31536000; includeSubDomains"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-alertmanager
  namespace: prometheus
  labels: #@ labels("httproute")
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: envoy-gateway-system
    sectionName: alertmanager
  hostnames:
  - alertmanager.{{{ .environment.domain }}}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: prometheus-alertmanager
      port: 9093
    matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        set:
        - name: Strict-Transport-Security
          value: "max-age=31536000; includeSubDomains"

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus-server
  namespace: prometheus
  labels: #@ labels("security-policy")
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: prometheus-server
  oidc:
    provider:
      issuer: https://dex.{{{ .environment.domain }}}/dex
    clientID: envoy-gateway
    clientSecret:
      name: prometheus-oidc-client-secret
    redirectURL: https://prometheus.{{{ .environment.domain }}}/oauth2/callback
    logoutPath: /logout

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus-alertmanager
  namespace: prometheus
  labels: #@ labels("security-policy")
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: prometheus-alertmanager
  oidc:
    provider:
      issuer: https://dex.{{{ .environment.domain }}}/dex
    clientID: envoy-gateway
    clientSecret:
      name: alertmanager-oidc-client-secret
    redirectURL: https://alertmanager.{{{ .environment.domain }}}/oauth2/callback
    logoutPath: /logout

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-oidc-client-secret
  namespace: prometheus
  labels: #@ labels("oidc-secret")
type: Opaque
stringData:
  client-secret: {{{ .dex.oidc_client_secret }}}

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-oidc-client-secret
  namespace: prometheus
  labels: #@ labels("oidc-secret")
type: Opaque
stringData:
  client-secret: {{{ .dex.oidc_client_secret }}}
