#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"grafana"}}), expects=1
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.subset({"name":"grafana"}), expects=1
      - name: grafana
        #@overlay/replace
        resources: #@ data.values.grafana.resources
