#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@ if len(data.values.grafana.username) == 0:
  #@  assert.fail("grafana.username cannot be empty")
  #@ end
  #@ if len(data.values.grafana.password) == 0:
  #@  assert.fail("grafana.password cannot be empty")
  #@ end
  admin-user: #@ data.values.grafana.username
  admin-password: #@ data.values.grafana.password
