#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.grafana.username) == 0 or data.values.grafana.username == "username":
#@  assert.fail("grafana.username is missing or invalid")
#@ end
#@ if len(data.values.grafana.password) == 0 or data.values.grafana.password == "password":
#@  assert.fail("grafana.password is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana
  labels: #@ labels()
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  admin-user: #@ data.values.grafana.username
  admin-password: #@ data.values.grafana.password
