#@data/values
---
#@overlay/match missing_ok=True
secrets:
  hetzner:
    token: deadbeef-beefdead
    ssh:
      public_key: 'ssh-rsa keykeykeykeykey kubernetes'
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        keykeykeykeykey
        -----END RSA PRIVATE KEY-----

  ingress:
    basic_auth:
      username: username
      password: password
    oauth:
      cookie_secret: secret
      client_id: id
      client_secret: secret

  lets_encrypt:
    email: 'nobody@nobody'
    prod_key: 'none'
    staging_key: 'none'

  postgres:
    password: password
    backup:
      s3:
        access_key_id: access_key
        secret_access_key: secret_key
        endpoint: http://example/deadbeef
        bucket: bucketname

  grafana:
    username: username
    password: password

  alertmanager:
    email:
      host: smtp.gmail.com:587
      mail_from: 'nobody@nobody'
      mail_to: 'nobody@nobody'
      password: password
    teams_webhook:
      url: http://example/deadbeef
