# client
[Interface]
Address = {{{ .hetzner.wireguard.client.ip }}}
PrivateKey = {{{ .hetzner.wireguard.client.private_key }}}

[Peer]
PublicKey = {{{ .hetzner.wireguard.server.public_key }}}
Endpoint = {{{ .environment.domain }}}:{{{ .hetzner.wireguard.server.port }}}
AllowedIPs = {{{ .hetzner.wireguard.server.range }}}, {{{ .hetzner.private_network.subnet }}}
PersistentKeepalive = 25
