# server
[Interface]
Address = {{{ .hetzner.wireguard.server.ip }}}/24
ListenPort = {{{ .hetzner.wireguard.server.port }}}
PrivateKey = {{{ .hetzner.wireguard.server.private_key }}}

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o ens+ -j MASQUERADE
PostUp = sysctl -w -q net.ipv4.ip_forward=1; sysctl -w -q net.ipv4.conf.all.forwarding=1
#PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o ens+ -j MASQUERADE
#PostDown = sysctl -w -q net.ipv4.ip_forward=1; sysctl -w -q net.ipv4.conf.all.forwarding=1
SaveConfig = false

# client
[Peer]
PublicKey = {{{ .hetzner.wireguard.client.public_key }}}
AllowedIPs = {{{ .hetzner.wireguard.client.ip }}}/32
