#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.postgres.password) == 0 or data.values.postgres.password == "password":
#@  assert.fail("data.values.postgres.password is missing or invalid")
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: postgres
  labels: #@ labels("secret")
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: #@ data.values.postgres.password
  PGDATA: /var/lib/postgresql/data/pgdata
  DB_HOST: "127.0.0.1"
  DB_PORT: "6432"
  DB_USER: postgres
  DB_PASSWORD: #@ data.values.postgres.password
