#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.postgres.storage.class_name) == 0:
#@  assert.fail("data.values.postgres.storage.class_name cannot be empty")
#@ end
#@ if len(data.values.postgres.storage.size) == 0:
#@  assert.fail("data.values.postgres.storage.size cannot be empty")
#@ end

#@ if data.values.postgres.storage.reclaim:
#@ if len(data.values.postgres.storage.volume_handle) == 0:
#@  assert.fail("data.values.postgres.storage.volume_handle cannot be empty")
#@ end
#@ if len(data.values.postgres.storage.driver) == 0:
#@  assert.fail("data.values.postgres.storage.driver cannot be empty")
#@ end
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-postgres
  namespace: postgres
  labels: #@ labels("pv")
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: #@ data.values.postgres.storage.size
  csi:
    driver: #@ data.values.postgres.storage.driver
    fsType: ext4
    volumeHandle: #@ str(data.values.postgres.storage.volume_handle)
  storageClassName: #@ data.values.postgres.storage.class_name
#@ end

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: postgres
  labels: #@ labels("pvc")
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.postgres.storage.size
  storageClassName: #@ data.values.postgres.storage.class_name
  #@ if/end data.values.postgres.storage.reclaim:
  volumeName: pvc-postgres
