#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("_ytt.lib.yml", "labels")

#@ if len(data.values.postgres.resources.storage.class_name) == 0:
#@  assert.fail("postgres.resources.storage.class_name cannot be empty")
#@ end
#@ if len(data.values.postgres.resources.storage.size) == 0:
#@  assert.fail("postgres.resources.storage.size cannot be empty")
#@ end

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: postgres
  labels: #@ labels("pvc")
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.postgres.resources.storage.size
  storageClassName: #@ data.values.postgres.resources.storage.class_name

#@ if data.values.pgbackup.enabled:
#@ if len(data.values.pgbackup.resources.storage.class_name) == 0:
#@  assert.fail("pgbackup.resources.storage.class_name cannot be empty")
#@ end
#@ if len(data.values.pgbackup.resources.storage.size) == 0:
#@  assert.fail("pgbackup.resources.storage.size cannot be empty")
#@ end

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgbackup
  namespace: postgres
  labels: #@ labels("pvc")
  annotations:
    kapp.k14s.io/change-group.pgbackup: pgbackup-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.pgbackup.resources.storage.size
  storageClassName: #@ data.values.pgbackup.resources.storage.class_name
#@ end
