#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    k8s-app: headlamp
  annotations:
    kapp.k14s.io/versioned: ""
type: Opaque
stringData:
  #@ if len(data.values.dashboard.kubeconfig) == 0:
  #@  assert.fail("dashboard.kubeconfig cannot be empty")
  #@ end
  config: #@ data.values.dashboard.kubeconfig
