#@data/values
---
#@overlay/match missing_ok=True
configuration:
  hetzner:
    node:
      name: {{{ .hetzner.node.name }}}
      type: {{{ .hetzner.node.type }}}
      image: {{{ .hetzner.node.image }}}
      location: {{{ .hetzner.node.location }}}

    firewall:
      enabled: "{{{ .hetzner.firewall.enabled }}}"
      name: {{{ .hetzner.firewall.name }}}

    floating_ip:
      enabled: "{{{ .hetzner.floating_ip.enabled }}}"
      name: {{{ .hetzner.floating_ip.name }}}

    loadbalancer:
      enabled: "{{{ .hetzner.loadbalancer.enabled }}}"
      name: {{{ .hetzner.loadbalancer.name }}}
      type: {{{ .hetzner.loadbalancer.type }}}

  ingress:
    domains:
    - {{{ .environment.domain }}}

  postgres:
    backup:
      s3:
        enabled: "{{{ .postgres.backup.s3.enabled }}}"
        retention_days: {{{ .postgres.backup.s3.retention_days }}}

  alertmanager:
    email:
      enabled: "{{{ .alertmanager.email.enabled }}}"
