---
version: '3'
set: [errexit, nounset, pipefail]

tasks:
  default:
    desc: "List all tasks"
    cmds:
    - task -l

  setup:
    desc: "Setup environment"
    cmds:
    - bash setup.sh

  deploy:
    desc: "Deploy entire infrastructure and components"
    # deploy it all, all of it!
    cmds:
    - task: setup
    # setup cluster on hetzner cloud
    - task: hetzner:deploy
    # let's own the kube-system namespace
    - task: kube-system:deploy
    # we need some fancy gateway-api routing
    - task: envoy-gateway:deploy
    # and automatic let's encrypt certificate management
    - task: cert-manager:deploy
    # and use github oauth/oidc
    - task: dex:deploy
    # it also never hurts to have a dashboard!
    - task: headlamp:all
    # # we can always use a good database..
    - task: postgres:deploy
    # metrics, monitoring, alerting, logs, what would we do without those?
    - task: prometheus:all
    - task: loki:all
    - task: vector:deploy
    - task: grafana:deploy
    # admire our work!
    - task: list-apps
    # cleanup properly afterwards ...
    - task: cleanup

  list-apps:
    desc: "List all running apps/components"
    cmds:
    - bash list_apps.sh

  cleanup:
    desc: "Cleanup environment, remove confidential files"
    cmds:
    - bash cleanup.sh

  update-charts:
    desc: "Update all helm charts"
    cmds:
    - bash dex/build/update.sh
    - bash grafana/build/update.sh
    - bash headlamp/build/update.sh
    - bash loki/build/update.sh
    - bash prometheus/build/update.sh
    - bash vector/build/update.sh

includes:
  hetzner: ./hetzner-k3s
  kube-system: ./kube-system
  envoy-gateway: ./envoy-gateway
  cert-manager: ./cert-manager
  dex: ./dex
  headlamp: ./headlamp
  postgres: ./postgres
  prometheus: ./prometheus
  loki: ./loki
  vector: ./vector
  grafana: ./grafana
