#@data/values
---
ingress:
  enable_network_policy: true

  resources:
    requests:
      cpu: 150m
      memory: 192Mi
    limits:
      cpu: 1000m
      memory: 384Mi

basic_auth:
  image: "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  replicas: 1
