#@data/values
---
ingress:
  enable_network_policy: true

  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi

basic_auth:
  image: "jamesclonk/basic-auth:678636aaca212f20c4e263d05b75efabdc6aef2c"
  replicas: 1
