#@ load("@ytt:data", "data")
#@ load("_ytt.lib.yaml", "labels")

---
apiVersion: v1
kind: Secret
metadata:
  name: static-user
  namespace: dex
  labels: #@ labels()
type: Opaque
stringData:
  email: "{{{ .dex.static_user.email }}}"
  username: "{{{ .dex.static_user.username }}}"
  password: "{{{ .dex.static_user.password }}}"
