name: Kubernetes Infrastructure

on:
  push:
    branches: [ master ]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Provision whole Kubernetes infrastructure
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        HETZNER_PUBLIC_SSH_KEY: ${{ secrets.HETZNER_PUBLIC_SSH_KEY }}
        HETZNER_PRIVATE_SSH_KEY: ${{ secrets.HETZNER_PRIVATE_SSH_KEY }}
        INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}
        LETS_ENCRYPT_EMAIL_ADDRESS: ${{ secrets.LETS_ENCRYPT_EMAIL_ADDRESS }}
        DASHBOARD_BASIC_AUTH_USERNAME: ${{ secrets.DASHBOARD_BASIC_AUTH_USERNAME }}
        DASHBOARD_BASIC_AUTH_PASSWORD: ${{ secrets.DASHBOARD_BASIC_AUTH_PASSWORD }}
      run: ./deploy.sh
