name: Kubernetes Infrastructure

on:
  push:
    branches: [ master ]

jobs:
  provision:
    if: "!contains(github.event.head_commit.message, 'skip')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Provision whole Kubernetes infrastructure
      env:
        HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        HETZNER_PUBLIC_SSH_KEY: ${{ secrets.HETZNER_PUBLIC_SSH_KEY }}
        HETZNER_PRIVATE_SSH_KEY: ${{ secrets.HETZNER_PRIVATE_SSH_KEY }}
        INGRESS_DOMAIN: ${{ secrets.INGRESS_DOMAIN }}
        INGRESS_BASIC_AUTH_USERNAME: ${{ secrets.INGRESS_BASIC_AUTH_USERNAME }}
        INGRESS_BASIC_AUTH_PASSWORD: ${{ secrets.INGRESS_BASIC_AUTH_PASSWORD }}
        LETS_ENCRYPT_EMAIL_ADDRESS: ${{ secrets.LETS_ENCRYPT_EMAIL_ADDRESS }}
        LETS_ENCRYPT_PROD_KEY: ${{ secrets.LETS_ENCRYPT_PROD_KEY }}
        LETS_ENCRYPT_STAGING_KEY: ${{ secrets.LETS_ENCRYPT_STAGING_KEY }}
        PROMETHEUS_ALERTMANAGER_EMAIL_ENABLED: ${{ secrets.PROMETHEUS_ALERTMANAGER_EMAIL_ENABLED }}
        PROMETHEUS_ALERTMANAGER_EMAIL_HOST: ${{ secrets.PROMETHEUS_ALERTMANAGER_EMAIL_HOST }}
        PROMETHEUS_ALERTMANAGER_EMAIL_PASSWORD: ${{ secrets.PROMETHEUS_ALERTMANAGER_EMAIL_PASSWORD }}
        PROMETHEUS_ALERTMANAGER_EMAIL_FROM: ${{ secrets.PROMETHEUS_ALERTMANAGER_EMAIL_FROM }}
        PROMETHEUS_ALERTMANAGER_EMAIL_TO: ${{ secrets.PROMETHEUS_ALERTMANAGER_EMAIL_TO }}
        PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_ENABLED: ${{ secrets.PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_ENABLED }}
        PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_URL: ${{ secrets.PROMETHEUS_ALERTMANAGER_TEAMS_WEBHOOK_URL }}
      run: ./deploy.sh
