name: kubernetes infrastructure

on:
  push:
    branches: [ develop ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENVIRONMENT: development

jobs:
  kind:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: kind-integration-testing
    needs: [ hetzner-k3s ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run complete infrastructure deployment
      run: ./deploy.sh
    - name: cleanup
      if: ${{ always() }}
      run: ./cleanup.sh
