name: kubernetes infrastructure and cluster

on:
  push:
    branches: [ master ]

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

jobs:
  hetzner-k3s:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: kubernetes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: install and upgrade k3s on hetzner cloud
      run: task hetzner:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  kube-system:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: kube-system
    needs: [ hetzner-k3s ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: prepare kube-system namespace
      run: task kube-system:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  envoy-gateway:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: envoy-gateway
    needs: [ kube-system ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: deploy kubernetes gateway-api controller
      run: task envoy-gateway:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  cert-manager:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: cert-manager
    needs: [ envoy-gateway ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy cert-manager for let's encrypt
      run: task cert-manager:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  dex:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: dex
    needs: [ cert-manager, envoy-gateway ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: deploy dex
      run: task dex:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  headlamp:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: headlamp
    needs: [ dex, cert-manager ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy headlamp
      run: task headlamp:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  postgres:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: postgres
    needs: [ kube-system ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy postgres database
      run: task postgres:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  prometheus:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: prometheus
    needs: [ dex, cert-manager, kube-system ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy prometheus
      run: task prometheus:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  loki:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: loki
    needs: [ dex, cert-manager ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy loki
      run: task loki:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  vector:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: vector
    needs: [ prometheus, loki ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy vector
      run: task vector:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  grafana:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: grafana
    needs: [ prometheus, loki ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install wireguard tools
      run: ./github_wireguard.sh
    - name: setup
      if: ${{ always() }}
      run: ./setup.sh
    - name: deploy grafana
      run: task grafana:deploy
    - name: cleanup
      if: ${{ always() }}
      run: task cleanup

  testing:
    if: "!contains(github.event.head_commit.message, 'skip')"
    name: k8s e2e testing
    needs: [ postgres, grafana, headlamp ]
    runs-on: ubuntu-latest
    steps:
    - name: checkout k8s-testing
      uses: actions/checkout@v3
      with:
        repository: JamesClonk/k8s-testing
        ref: master
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: setup chrome
      uses: ./.github/actions/setup-chrome

    - uses: actions/checkout@v3
      with:
        path: repo
    - name: install wireguard tools
      working-directory: repo
      run: ./github_wireguard.sh
    - name: setup kubeconfig
      working-directory: repo
      run: ./setup.sh

    - name: run k8s-testing specs
      run: |
        export KUBECONFIG=${HOME}/.kube/k8s-infrastructure
        make test

    - name: cleanup
      if: ${{ always() }}
      working-directory: repo
      run: |
        rm -f ${HOME}/.kube/k8s-infrastructure || true
        ./cleanup.sh
