name: run specs on cluster

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing:
    name: 'k8s e2e testing'
    runs-on: ubuntu-latest

    steps:
    - name: checkout k8s-testing
      uses: actions/checkout@v3
      with:
        repository: JamesClonk/k8s-testing
        ref: master
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: setup chrome
      uses: ./.github/actions/setup-chrome

    - uses: actions/checkout@v3
      with:
        path: repo
    - name: setup kubeconfig
      working-directory: repo
      run: ./setup.sh
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    - name: run k8s-testing specs
      run: |
        export KUBECONFIG=${HOME}/.kube/k8s-infrastructure
        make test

    - name: cleanup
      if: ${{ always() }}
      working-directory: repo
      run: |
        rm -f ${HOME}/.kube/k8s-infrastructure || true
        ./cleanup.sh
