name: run specs on cluster

on:
  workflow_dispatch:

env:
  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

permissions:
  contents: read

jobs:
  testing:
    name: 'k8s e2e testing'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup kubeconfig
      run: ./setup.sh

    - name: checkout k8s-testing
      uses: actions/checkout@v3
      with:
        repository: JamesClonk/k8s-testing
        ref: master
        path: testing
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: setup chrome
      uses: ./testing/.github/actions/setup-chrome
    - name: run k8s-testing specs
      working-directory: testing
      env:
        KUBECONFIG: ~/.kube/k8s-infrastructure
      run: |
        make all

    - name: cleanup
      if: ${{ always() }}
      env:
        KUBECONFIG: ~/.kube/k8s-infrastructure
      run: |
        rm -f ${KUBECONFIG} || true
        ./cleanup.sh
